<?php $pageTitle = "SCC-01"; include($_SERVER['DOCUMENT_ROOT']."/includes/header.php"); ?>

<h3>Suncrest County Chronicles #1</h3>
<h1>The New Professor in Suncrest County</h1>
<div>
<p>There wasn’t a cloud in the sky the day I moved in.  I had heard the weather in Suncrest County could be temperamental, but I like to think it had been welcoming me in.  I carried boxes upon boxes in that late summer sun through the door of my new home.  It took hours, but all the work made it go by shockingly fast.  By the time I was finished, the movers had arrived to take their truck back.  I made sure to do a once over before letting them go and stood in front of my new home feeling proud, if not a little nervous.  I had never owned a home before.  It was always apartments in cities, never a house in the suburbs halfway across the country.  I’ve got to get mom and dad out here when I can just to see how nice this place looks.  I spent much of the first day unpacking and figuring out where work was.  That being a college campus a few towns over, at which I was to be a professor.  The drive wasn’t exactly short, but it would give me time to take in the scenery of the surrounding area: small towns with long strips of forest between.  
I had been flattening the boxes I was done with and putting them in the corner by the door just to get them out of the way.  Before it got dark, I tried tying them up, but the freshly waxed oak floors really made it quite the chore, sliding around and such.  Fortunately, I managed to do that before the sun went down and continued to sort through boxes and place them in piles to head to their proper rooms.  At first, all was well until I noticed a particular box was missing.  I know I packed it.  It had a big yellow flower on the side so I knew which it was.  I definitely didn’t unpack it already.  I took a quick stroll around the house to see if it had been misplaced in any of the rooms, but that was just not so.  Confused, I called up the moving company to see if they could check the truck I used.  They told me the truck was empty, which made sense since I certainly left it that way.  I decided not to stress too much about it and figured it was probably under some other boxes I hadn’t gotten to yet along the wall and called it a night.

The next two days were uneventful, to say the least.  Just unpacking and cooking up the food I had brought with me.  Nothing special, mostly canned goods.  I thought though that sometime soon I should find the grocery store and pick up some perishable goods.  Thinking about it, I don’t think I had seen anyone out and about since I moved in.  Then again, I had only been here a couple of days and barely left my house. 
The next morning was the first day of school.  I was a bit on edge due to some mistakes on the part of the administration, but hopefully it wouldn’t cause any issues.  As I closed the door behind me and walked out I noticed a school bus putting down its stop sign and getting on the move again.  That’s why there hasn’t been anyone around on these nice days, the local schools started session before the college does.  I embarrassedly patted my palm to my forehead and went on my way.  Just first-day jitters.  The route I decided to drive was nice, taking me through the woods between each town, I took note of the signs as I pass them.  Entering Harrison, then Torby, then Bankton, then finally just past the sign for Corsia was the college.  
There was only one class I had to teach today, European Mythology.  I had always had an interest in the pantheons of old, especially the Norse, with their depictions of Ragnarök and the end of someone’s world.  Regardless, much to my surprise, the class went off without a hitch!  As I was packing my things up, a student stayed behind and got my attention.  He said his name was Christopher and asked if I was alright.  I told him of course I was, just excited to teach!  But he brought up some of the technical difficulties I had when trying to show my notes to the class.  I decided to come clean and tell him that the administration had a bit of a mix-up with myself and another professor and it caused them to not have everything ready yet.  He was understanding and asked about my office hours.  I hadn’t even thought about that yet, then told him I didn’t even have an office yet, but would let him know after a future class when I had been assigned one.  
After waving goodbye I remembered I didn’t have any other classes today, so I thought it best to head home.  I was looking forward to it, the midday sun shining through the trees and all.  And of course the delightful signs of each town.  Corsia’s regal yellow, Bankton’s vibrant emerald, Torby’s elegant crimson, and Harrison’s brilliant sapphire.  Funnily enough,  I had read before moving that the sign for my town had been taken down to be refurbished due to some graffiti, so now there’s just a “Now Leaving Harrison” sign glistening in its place.  The cool breeze as I stepped out of my car was pleasant and I looked around to really get a good look at my neighbors’ homes.  They looked just like mine except the colors were different.  The previous owner of my home must’ve been quite the clean freak because the paint on the others’ was not nearly as fresh and bright, though, I found the more muted pastels to fit the space quite nicely.  I thought again about how there wasn’t anyone out but again realized it was the middle of the day.  Children were at school and their parents were at work.  All it took was just one look at everyone’s driveways to realize that.
I continued unpacking as there were still quite a few boxes to go.  I didn’t realize until I stored up my life in cardboard that I had so many things.  I was honestly a bit overwhelmed but knew it would be done within a few days and I could satisfyingly toss my growing mountain of cardboard.  One thing already greatly unpacked was a veritable mountain of soup my mother had given me before I left.  Chicken noodle was on the menu for dinner.  As I sat in the dining room eating, I remembered that I couldn’t find that one box the day I moved in, so I got up and went to look around again, thinking it might’ve been uncovered.  However, no matter where I looked, it was nowhere to be found.  I picked up every box and examined all six sides.  No flower to be seen.  I was beginning to get agitated.  There was no way I didn’t bring it.  It HAS to be here.
I don’t know what I’ll do if it’s not here.  I took a deep breath and went to finish my soup.  As I sat down I realized the spoon wasn’t in the bowl.  Did I drop it?  I ducked under the table to check.  No, it wasn’t there.  I looked around all over the kitchen, then back in the living room in case I brought it with me.  Not any of those places either.  What the hell was happening?  First I misplace a box and now my spoon?  It was ridiculous!  I kicked one of the boxes out of frustration and heard the sound of something inside shatter.  I dropped to the floor immediately concerned with what I broke.  But I didn’t open the box — I just sat there — thinking.  I had thought that the move was getting to me.  Mom and dad didn’t want me to go so far away from family and friends.  And who knows what the neighbors were going to think of me.  And I could end up being a terrible teacher.  And… and… and… that goddamned box!
A loud knock at the door brought me to my feet.  I noticed what I had been doing and neatened myself up as the knocking continued.  I quickly opened the door to see a blonde woman about my age in a shirtwaist dress standing in front of me.  She introduced herself as my neighbor in the pink house to the right.  She mentioned how I hadn’t introduced myself to anyone yet and thought I must be shy so she came over herself.  I thought the gesture was nice since I had been quite the shut-in so far.  As I was about to respond I realized it had gotten pretty cloudy and wondered when that happened.  I joked to her about how my warm welcome from nature had run out and I must just be part of the community now, then asked her why it feels like there was never anyone out and about in town.  She seemed to tense up for a second before asking how I’d even be able to tell with how much I’d been inside and that new move anxiety must be getting to me, before excusing herself saying that she needed to get back and prepare dinner before her husband got home.  As she briskly walked away, I thought about what she said and realized she was probably right, I was being silly for fixating on that.
I returned to the kitchen to find my soup bowl empty in my sink with the spoon resting along the edge of it.  I must’ve finished it and done so without really thinking about it.  Huh.
The following day I went about the journey back to campus, but this time for a meeting with the administration.  As always, the continuous comfort I found in the town signs kept me on my path, Harisson, Torby, Bamkton, Corsia.
The meeting was short, however, it was not insignificant.  An office was finally assigned to me and I was given an ID and some other paperwork that needed to be filled out.  I had to teach a couple of classes afterward, Asian and African Mythology respectively.  Truthfully though, I can’t say much of note happened besides trying to get students to engage in the class a little.
With the first days of each of my classes finally through, I sought out my new office.  On the third floor of the Roberts building was the room in question, 323.  It was small but decorated finely with Victorian-style wooden furniture.  Several dark empty bookshelves lined the sides of the room with a great big desk in the middle near the rear.  Behind that was a large window letting in a great deal of natural light.  I realized then that there weren’t any electrical lights I could turn on in the office at all.  Hopefully the school didn’t mind candles when it got dark.
Since I was essentially all unpacked back home, I sat down at the desk, running my fingers along the polished edge before I opened a book I had picked up in an old bookstore along the drive from my previous apartment.  The cover was nothing special, but the title intrigued me greatly.  So I spent some time in the office, gradually flipping each page as I read.  I was enraptured by it.  The tension the author was capable of building up had me holding my breath.  
A sudden bang made my gaze shoot up to the door as I dropped my book on the desk.  A draft must’ve slammed the door shut.  I suppose I left it open.  I could feel my heart beating intensely.  Had the book done that to me?  I looked down, closed it, then turned to the window behind me.  The growing stormy weather convinced me it was a good time to head home.  Didn’t want to drive in the rain after all.
Unfortunately for me, the rain had begun by the time I reached my street, though it was only a slight drizzle it was a clear sign of what was to come with the dark overbearing clouds above.  As I neared my home I noticed my blonde neighbor was outside gardening in the flowerbed in front of her house.  Her husband must make a lot for her to stay at home like this all day.  Like a proper neighbor I pulled over and intended to inform her of how the weather was going to develop so I called out and waved.  She looked up and shared the exchange.  However, I was taken aback at the sight of what appeared to be blood running down her arm.  Immediately I brought attention to it and she looked concerned, not that it was happening, but that I brought it up.  She apologized and held her arm down, blood out of view.  She quickly suggested that she must’ve cut herself while opening seed packets and didn’t notice.  Finally, I return to my senses and suggest she go inside as the rain is liable to worsen soon.  She shrugged it off and told me she’ll be fine.
Seeing as though I had no other course of action but to head home, I waved goodbye and pulled into my driveway.  I walked into the house.  I threw my book onto the coffee table, then turned on the television as I dropped down onto the couch.  I sat there for a short bit, just watching the evening news until I passed out.
A violent crack of thunder woke me from my slumber as my body shot up, eyes rapidly darting around the room out of fear.  My eyes lingered on the window behind the television.  I gradually forced my body to stand, stepping over to the dark window.  With how hard the rain was coming down, it was difficult to see anything, but one shape stood out to me.  That woman was still walking around and gardening in the near-black pouring rain!  Eyes wide, I sprinted over to the door and swung it open.  I ran out onto the doorstep so fast I almost slipped.  I whipped my head to the right with my mouth open about to yell for her.  As I turned my head it sunk in that I never learned her name.  It didn’t matter.  By the time my eyes adjusted, there was nothing outside but rain.
I felt a sickness well up in my stomach the more confused I became.  Defeated and perturbed, I returned to the couch.  It seems must’ve turned the television off before I got up.  No matter, there were classes tomorrow and I needed to go back to sleep.
There were no beams of light trickling through the leaves that morning as the whole county appeared to be coated in thick fog from the storm the night prior.  It didn’t change anything about the drive, just that I had to take it a bit slower.  More time to appreciate the scenery I supposed.  And as always there were my beloved progress markers along the way: Harrison, Bankton, Corsia.  The vibrancy of each almost seemed to glow through the fog as I passed them.  
The lecture that day was the same as two days before, European Mythology.  As class was ending I noticed the student that had stayed back the first day was leaving.  I called out to Chester and he turned to descend the steps of the lecture hall.  He looked at me puzzled as I told him where my office is and what the hours were.  He was confused as to why I was telling him this.  As I mentioned that he asked a few days ago, he quickly acknowledged that I was right, thanked me, then rushed out of the room.  
As I began to venture toward the parking lot I had to shield my eyes from the light.  Finally, the clouds had parted and the fog had subsided.  As I drove I again saw the sign for the Bankton after leaving Corsia and was compelled to stop in town for some food.  I parked at a quiet little place called Heywood’s Pizza.  There were long red fluorescent lights along edges and corners, inside and out, reflecting hazily off the checkered floor.  It looked more like an old diner from New Jersey than a pizza place, but nonetheless it smelled of greasy food and that was all I desired.  The cashier was college-aged.  I asked him if he went to the college in Corsia, to which he said ‘no’.  Then I asked him if he had ever been to my town, to which again he said ‘no’, then demanded I order something.  
I continued along the winding forested path with a steaming pizza resting in the passenger seat.  Torby, Harrison, home, finally.  I parked and walked up to my neighbor’s home, thinking it may be nice to finally meet the husband and invite them over for dinner.  Pizza wasn’t the fanciest thing, but it was fairly inoffensive.  Who didn’t like pizza?  I knocked on the door, knowing the husband should be home by now.  However, I received no response.  I knocked again, calling out to them as well.  But again, no response.  I paused.  The moment I banged my fist against the door a third time, it dented inward.  That wooden door had just dented inward like a rock to a car.  I stepped back in shock and yelled for them with a wavering tone.  There were two cars in the driveway.  I started to panic.  I thought about how something might’ve happened to them.  I had just seen the wife yesterday.  Without thinking I grabbed the cool bronze doorknob and twisted it.  It snapped off like fragile plastic.  I fell back onto the porch, shaking.  I was gripping the knob hard.  In an instant I rid myself of it.  I scrambled to stand again, my eyes darting around the nearby houses to see if anyone had witnessed what I had just done.  Without actually making sense of what I saw, I sprinted back to my home and locked the door.  I pressed my back to it as I slowly slid down telling myself over and over and over and over and over and over and over again that what had happened was weird.
Before I knew it, I had set up a small table and chair against the window that looked out to my neighbor’s home and left a small crack in the blinds to peer through.  Clearly my neighbors were in no place to come over for a dinner invitation, so I ate that pizza myself, gaze fixed on that porch out the window.  I did however get up once to head to the restroom, but upon returning I was struck with an immense feeling of shock.  I saw the clock in the hall… hours had passed since I got up.  Hurriedly I made my way to the table and tore the blinds open, the sky was black and the pizza had gone cold.  How long was I in there…?  I grabbed the open bottle of vodka on the table and took a swig, perhaps I just needed to sleep.

The following morning I took a longer way to campus, not driving past my neighbor’s house, not even looking in that direction when I stepped out my door.  My head felt foggy as I drove, no doubt influenced by the dull cloudy morning sky above.  As I went, I looked to the Corsia sign and said its name aloud.  I’m not sure why, it just felt right, like something to help me cling to my sanity after last night.  I had no upcoming classes to teach, however, I was liable for the office hours posted by my bosses in the administration.  Quietly, I lit a few candles around the office and unpacked some paperwork that needed tending to.  I didn’t get very far, however, as a young woman came knocking at my door.  One of my students.  I motioned for her to come in and slid my papers to the side of my desk.  As she sat down she introduced herself and began explaining her conundrum.
After about an hour I was able to assist her with her woes about the class thus far and reassured her that I had no intention of being an unfair teacher.  She did mention that she had been burned by professors in the past.  She waved as she left my office and I returned the gesture before returning to my… paperwork.  There wasn’t anything on my desk.  I leaned back in my chair to see if it had fallen onto the floor, but there was nothing there either.  I began feverishly searching around the room, lifting things up that the papers could never have been under when it dawned on me.  I leapt out the door to call out to the student.  But she too was gone.  As I stared down the long hallway I wondered just what I was looking at.  There wasn’t enough time for her to reach an exit and I certainly didn’t hear her running.  I rubbed the back of my head and pulled up into my driveway.  Out of the corner of my eye, I could see my neighbor waving to me, but I kept my eyes averted as best I could.  I kept my posture tight and went into my home without so much as uttering a word to her.
I sat slumped on the couch absentmindedly watching the television.  There was a knock at the door, but I dared not answer it.  Then was another, louder this time.  I didn’t move.  Then another, even louder.  I closed my eyes for a brief second in frustration.  Again there was repeated knocking on the door, louder and more violent than all the times before.  I angrily sprang to my feet, turning towards the long hallway to the door just to make it stop.  For the love of God please just stop.  Standing before me was my neighbor just a couple of feet away.  She looked concerned, worried almost.  She said the television wasn’t on.  I turned to it.  Oh, yeah.  I heard the sound of the door slam shut and turned back to see it closed.  Then I turned my head all over the living room in sudden frustration.  Where in Hell is that goddamned box?!  
I ran to the door and grabbed the knob to swing it open, but it was locked.  Feeling antagonized, I fiddled with all the locks until I could swing it wide open.  Raindrops began to fall as I manically rushed my way to my neighbor’s door.  I pounded on it with all the strength I had.  I screamed 
“Where is everyone?!” “What is going on?!?”  
The door slowly lurched open amidst my beatings.  A man who I could only assume was the husband answered my calls.  I could see the wife down the hall peeking around a corner, terrified.  The husband asked who I was.  I told him I was their new neighbor and I knew his wife as I pointed towards her.  He looked back.  She looked horrified.  He looked at me again.  The sound of rain had stopped.  The only thing I heard after that… no, the only thing I felt after that, was 
“Go.  Home.”
I closed my eyes and open them again.  It was pouring rain worse than I had ever seen before.  There was next to no visibility and I wasn’t sure if my car could handle it on these roads.  I wasn’t far from campus though.  I saw the town sign and parked under an overhanging roof.  There was no umbrella to keep me dry while I navigated to my office.  The door was locked?  I never locked my office.  I fumbled with my keys to find the right one, then went in.  It was incredibly dark and the back window had been left open.  It was clattering against the wall while rain covered everything nearby.  I closed the window and as I wiped my hand off, my eyes wandered over to the calendar on the wall.  I stood there transfixed by it for a moment, not understanding.        I wasn’t supposed to be here.
The rain wasn’t letting up as I drove back.  I was well beyond Corsia when I saw the sign of a town I didn’t recognize.  I didn’t know this place.  Did I take a wrong turn somewhere?  No, there were almost two turns the whole route.  I continued to drive around the immediate area until I found a bus stop.  I parked next to it and got out, ignoring the downpour.  I located the map of the bus routes and drew my finger around it till I found Corsia, then traced along the route I had always taken through the towns I passed all the way to my town.  My eyes darted around the immediate area of my finger.  My heart began beating in my ears as a panic arose within me.  My breathing hastened faster and faster until I felt my knees give out as I fell back onto the bench behind me.


It’s not there.
</p>
</div>

<nav>
    <a href="chapter2.php">Next Chapter →</a>
</nav>

<?php include($_SERVER['DOCUMENT_ROOT']."/includes/footer.php"); ?>
