<?php $pageTitle = "SCC-02"; include($_SERVER['DOCUMENT_ROOT']."/includes/header.php"); ?>

<h3>Suncrest County Chronicles #2</h3>
<h1>A Written Account on the Events of 12/21 as Witnessed by the Sole Survivor Clara Bishop</h1>
<div class=card>
<pre>	I suppose I should start when I was first made aware of the cult.  I was at work [on 12/15] doing my usual business, rifling through paperwork, taking calls, greeting coworkers as they came in, as you would expect.  But around noon, one of the men in the office, Bradley Sardini, came over to my desk and told me he was going to be out one day the following week and wanted me to let the boss know.  So of course I pulled out the proper form and began filling it out while asking him questions.  Things like:  What day is it?  Will it be all day?  Will you be using PTO?  Etc.  All was fine until I had asked him what his reasoning for being out was.  Now, Bradley had never put in notice ahead of time for being out before.  I can only imagine somebody told him what to do.  We run a friendly office environment like that.  Anyway, he fidgeted a bit and asked me how much detail he had to go into.  I had suggested — based on what was written on the form — he provide as much as was relevant.  It was strange though.  He kind of leaned back a bit before asking if we could go somewhere private to finish the form.  I got the attention of another coworker, Michael [Kirsty], and told him we’d be right back.  You know, just in case someone called the office in the meantime.  I went with Bradley out into the hall with a clipboard and asked him the same question as the last.  He told me that he was going to a friend’s company picnic.  I thought that was pretty peculiar since not only was it a weekday, but he’d be ditching our job for a picnic, in December no less!  So I prodded further, which made him look uncomfortable, but he relented.  The first thing out of his mouth was that his previous statement was a lie.  I couldn’t believe it.  He then went on to say that he was going to a religious retreat and felt ashamed of admitting it to his coworkers.  I thought it a bit odd since Bradley didn’t exactly appear as the God fearing type, but far be it for me to judge.  I had nearly finished writing that down, when he started talking again.  He said he felt awkward because it wasn’t Christian or anything like that.  It felt like he wanted to talk about it, but wouldn’t unless I lead the conversation.  I motioned over to the nearby chairs and we sat down while I asked him to tell me more.  I think he realized it was more genuine interest than policy after I put the clipboard down.  

	I think that was the moment that all of this really started.  I suppose the previous bit was just some background, but important background nonetheless.  He told me that he had recently joined a religious group in town after seeing an advertisement on a mat in the [Forge Lake] Diner.  He said that he had been feeling aimless and wasn’t feeling fulfilled by his work and wanted to try something new, so he turned to this group.  They welcomed him in and showed him kindness, while directing all his praise to prayer.  He was given directions to a place where they would be officially welcoming in new members and he was to attend so he could become a full fledged member himself.  That’s what the retreat was about.  He seemed excited and relieved to tell me this, since it seemed like he hasn’t told anyone else about it.  He then had the idea to ask me to come!  Truthfully, I was a bit worried about what could happen if I didn’t and said something about it to another coworker.  But I figured at the time it would probably be okay and told him I’d write up my own form for future absence.  
	
	I wrote down that I had to take my niece, Moravia [Friar], to the hospital (which actually would end up happening and my sister [Ginny Friar] greatly appreciated it).  However that was to be in the morning and the retreat was in the afternoon, so I wasn’t missing anything.  In the few days between, I had stopped off at the [Forge Lake] Diner a few times for breakfast and tried to take note of the advertisements on the placemats.  I guess Bradley must have first come there in November since there was no ad about any religious group to be seen since the ads changed out for December.  On the day of, he had said to come on an empty stomach, but I was far too hungry after the hospital visit to function like that, so on this particular trip to the [Forge Lake] Diner I ordered a slice of disco pizza.  Not the healthiest thing I know, but I had barely eaten all day.  While I waited on the food, I absentmindedly scanned around the room, seeing all the others that had a hankering for a nice cheap lunch.  I hadn’t thought about it at the moment, but I now wonder if any of those people were about to do anything as traumatic as I was about to experience.  I can’t recall if any of them were present at the “retreat” but the thought that someone who participated in putting me through that horror was having a nice day eating just a few feet away from me.

	When the time came for Bradley to pick me up [at 3:00 PM], I was sitting alone in my apartment reading a short story about a man freezing to death.  Grim, I know, but I had heard good things.  As I finished the final line of the last page my doorbell rang and sent me flying off the couch.  I think I had gotten so immersed that I forgot about my evening plans.  At the door of course was Bradley wearing a smile and some very casual clothing.  He then walked me to his beat up pickup, the vessel that would lead us to that terrible place.  I don’t know the street we were on, but I imagine you already know where it was.  It took about 30 minutes to reach the building from my apartment in Bankton.  We had gone to a much more rural area than I was used to.  I think it would still be considered suburban, but not by much.  We didn’t talk much on the drive.  The building we parked at looked to just be a large house with neighboring homes all around.  Before Bradley could even knock at the door, a bald man with sunglasses dressed in fiery red robes swung it open to greet us.  His smile was warm and his expression calming.  He instructed us to hang out coats up in the closet around the corner then join the others at the dining table.  We did so, but I couldn’t get the image of the man’s robes out of my mind.  Something felt too warm about him, but I dismissed the thought for Bradley’s sake.  If my being there made him feel more comfortable, then so be it.  Or so I thought at the time.

	Almost everyone at the table was also wearing those robes and sunglasses.  The only ones that weren’t were a few couples sitting around the table.  My mind began to wander.  The man who greeted us came by and told us that during dinner the “vessels for the ceremony would be prepared” and left for what I assume was the kitchen since he and some robed others came back soon after with plates of food.  We didn’t get to choose what we wanted to eat.  Far too charred hot dogs (without buns) and a side of poorly microwaved baked beans.  How… Patriotic?  Not exactly what I was expecting given the situation, truth be told.  Once I looked around though I saw that all of the robed attendants had steak.  My level of unease increased thinking about if this is how they really treat their initiates… and visitors.  Dinner was eaten in complete silence, save for the constant sounds of chewing.  No one spoke up due to the robed members stayed quiet.  I had finished my “meal” already by the time the man who greeted us sat down at the table, where he finally broke that dreadful silence and thanked everyone for coming.  He told us that once everyone had finished their plates and glasses they would begin the ceremony.  Then there was that disarming smile again, this time directed at me.  I didn’t like it.  He suggested I must be eager to move forward with the night since I was already finished.  I nervously agreed and said I was just excited for Bradley.  After this there was small chatter as dinner concluded as it seemed that initial barrier of quiet had been torn down, letting everyone exhale a bit easier.  Bradley leaned over to me with a hand on my shoulder, thanking me for what I said.  

	The greeter, who I now know was the leader of this group, aggressively stood up the moment he saw all food and drink was consumed, then motioned for everyone to follow him outside, two by two.  We followed his orders, which felt odd to me at the time, but I had not yet fully understood it.  It was far more sinister than I would have believed.  

	There were 15 of us outside, including the leader.  We gathered around a large unlit fire pit and sat on a mixture of old lawn furniture and camping chairs.  All except the leader.  There was no chair for him.  However, what I had not noticed initially was a large covered object nearby to where he was standing.  He gave a short speech about how it is essential that they consciously observe the sun before it retreated for the night.  He called it “not abandonment, but tough love”.  Once he finished, he tore the cover from the object, revealing a binocular telescope.  I felt worry well up in the back of my throat.  “Surely that was meant for after the sun went down”, I recall thinking to myself.


	However, one by one, each of couples had someone break off to gaze into the blinding light of the sun through the telescope.  I didn’t even have the chance to hold Bradley back before I realized he had already gone up.  Each person to view the telescope had a cloth placed in their mouth, likely to muffle any noises as they were held in place until the leader stopped them.  A few screamed.  The cloth didn’t help much.  I had trouble understanding what I was seeing.  It all seemed like I was cast into a horror film.  I wanted to go.  I wanted to run far away at that moment.  But I knew that if I tried, something bad would’ve happened to me.  Well, I didn’t know it then, but I’m sure you can’t blame me for believing that.  So I stood firm and tried not to wince when Bradley too began to scream.  It felt like it was over so quickly.  He soon returned to my side with the blue of his eyes bleached to a cold unnatural white.   He smiled, clearly in pain, but I could tell he thought he was doing the right thing.

	The leader’s voice boomed over the crowd before him.  I almost forgot we weren’t alone.  I hadn’t looked to the others who didn’t blind themselves.  Did they know this would happen to the person who brought them there?  Was I supposed to know this was going to happen?

	The leader removed his sunglasses as he spoke to reveal his own bleached eyes.  He thanked everyone again for attending and made a motion to some of the other robed individuals.  They too took off their sunglasses.  More of the same.  They fetched a fire pit from a shed and carried it over to the center of where we all were seated.  I gripped Bradley’s hand, afraid of what was going to happen next.  This was the wrong decision, as he took it as a sign of encouragement.  The leader drew out attention once more when he pulled out a small black bag.  He told us about how inside was “the pure essence of the sun’s passion”.  I didn’t understand until he showed us a radiant vial beaming with light, which illuminated the darkening sky.  In a swift motion, he violently cast it into the fire pit, setting it ablaze with a massive burst of heat.  It felt like my eyebrows were going to be singed off.  Fortunately they weren’t.  The fire rapidly died down into a tiny ember on one of the logs, only setting off a faint glow.  The leader then began chanting in a language I didn’t understand as he reached his hands into the fire pit.  He chanted one word over and over before finally speaking in English something I don’t think I’ll ever be able to forget: “The vessels will now bring forth much passion”. 

	It happened so quickly.  Bradly grabbed my left wrist and another man grabbed my  right.  My eyes darted around rapidly, everyone who had peered into the telescope was tightly clenching the wrists of the people on either side of them.  My heart sank.  I did not know what was going to happen, but I feared for my life.  The leader hastily chanted once more and this time the initiates repeated him.  The leader broke the log across his chest, making him chant faster.  I tried to pull away from Bradly but he was too strong.  

	What happened next, I can only describe as an act of a god.  I do not know if it was theirs or some other power, but it was not of this earth.  The exact moment the leader held hands with the initiates on either side of him, he burst into flames.  They were no ordinary flames.  They were glowing wild colors.  Colors I cannot describe.  Colors I had never seen before.  Colors I didn’t even know existed.  Then, the initiates next to him caught flame.  The “vessels” they held onto were frozen in fear and they too succumbed to the blaze.  One by one each person was alright and howled the most horrific screams into the sky.  Bradley and I were closer to the left side than the middle, so we would be soon to succumb as well.  I don’t think I had ever sweat so much as I did that night.  My heart was racing.  I was panicking, thinking of anything I could to escape.  The scream Bradley let out when his hand caught fire will haunt my dreams until the day I die.  He was in so much pain.  I wonder now if he regretted his actions up to that point, knowing what he was to endure.  I think that my awful sweating may have just saved my life.  As Bradley became engulfed in flame, I was able to tear my hand away and I proceeded to kick in the back of the knee of the initiate to my right.  Fortunately, the surprise made him let go of me.  I turned to run and had the following not happened, I would not have looked back.  Bradley, lunged for me, grasping for my forearm.  He touched me only for a second, but his handprint will be forever etched in my skin.    The sensation sent shockwaves through my body.  I felt pain, but I felt warmth as well, a knowing warmth.  I kicked back at him to push away and climbed over the fence.  I made it only a few houses away by the time the conflagration had become beyond repair.  I knew instantly that it was because I broke the circle.  I don’t know why I knew, but I did.  Had I stayed put, the members of that cult would have survived.  Then there was the explosion.  It echoed through the entire town I’ve been told.  Nearly in the neighborhood came out to see what had happened.  A vortex of unknowable fire was practically in their backyards after all.  I collapsed on the front steps of one of the nearby houses.  The couple that lived there called 911 as soon as they saw me, singed and writhing.

	And that’s when you guys showed up.  I know you’ll say that the fire wasn’t any special color.  It’s because you weren’t connected to them.  You couldn’t physically see what I could.  I know that this ritual has been carried out hundreds of times without fail.  And I know that I should fear for my life for being the first to disrupt it.  Part of me wants to go back and see what remains of the property.  But I already know that nothing remains.  If it weren’t for the witnesses, it would be as if it never happened.  As is the nature of their god.  I truly don’t want to believe that it exists, but I know better than that.  But you’ll just have to take my word for it.
</pre>
</div>

<nav>
    <a href="01.php">← Previous Chapter</a>
</nav>
<nav>
    <a href="03.php">Next Chapter →</a>
</nav>

<?php include($_SERVER['DOCUMENT_ROOT']."/includes/footer.php"); ?>
