<?php $pageTitle = "SCC-03"; include($_SERVER['DOCUMENT_ROOT']."/includes/header.php"); ?>

<h3>Suncrest County Chronicles #3</h3>
<h1>An Overdue Reunion</h1>
<div class=card>
<pre>	The air inside the blue SUV was quiet and tentatively tense as it flew down the long wooded road, passing tall pine trees on either side.  Over four hours had passed from its departure and detour into Pennsylvania before turning towards Southern New Jersey.  Words were spoken fewer and fewer as the trip dragged on.  Stephen hadn’t opened his mouth in almost three hours now.  He felt the strange tension welling up and rolled down the front windows, his more so than the other, letting the air stir wildly.  The sudden blast of wind across the passenger seat made Andrzej send his back up in a hurry, but not all the way.  Stephen quickly apologized to his friend, this being the first time the two had seen each other in two years.  That was back in college still.  In spite of their recent communication on and off over the past few weeks, Stephen still felt uneasy about the situation.  He was excited to go camping with his best friend, though he wasn’t sure if he should consider Andrzej that anymore, or rather, if Andrzej considered him that anymore.  

	Andrzej told him not to worry, after all, Stephen knew it was just a habit of his to put the window up.  They’ve known one another since third grade, of course he knew it was a habit.  Stephen thought about when they first met, a Polish immigrant from New York with a strange accent walked into his classroom with a bright red backpack clasping his hands together nervously and looking at the floor while his parents gently ushered him forward.  Young Stephen was mesmerized by the way the boy spoke and when the teacher asked if anyone would want to come show him around the school, Stephen’s hand shot up immediately.  They were inseparable ever since.  That was until the end of college.

	Stephen’s thoughts grew sour once his mind reached that point.  He gripped the steering wheel harder.  The moment had played over and over in his mind countless times in the last two years.  A very drunk fight with one too many resentments that built up over the years and didn’t have the chance to spill into the light until then.  

	Stephen glanced into his rear view mirror, looking at all the supplies the two had packed.  They only planned to be out there for a couple days, but it looked like so much.

	In spite of their strong bond, they were never very open about their emotions with one another.  It came as a surprise when Andrzej, having had a bit too much to drink, started the fight based on those very grounds.  It didn’t begin *as* a fight however, it was much more akin to a cry for help.  Andrzej lashed out at Stephen about how they never spent time together anymore, how he was always with his new freshman girlfriend.  From there, it spiraled into two young men, incapable of handling the situation responsibly, yelling past one another, until one finally broke.

	The long stoplights were the most agonizing.  When the car wasn’t moving, all there was to do was sit in silence.  Stephen desperately wanted to turn on some music so they were less alone with their thoughts, but he knew the act in and of itself would be acknowledging and avoiding the awkwardness and that would be even worse.

	Andrzej kicked Stephen out.  He knew that with the Bankton Family wealth Stephen would get home safely somehow.  No matter how angry he was, Andrzej still was a little concerned about his friend’s safety.

	They passed by a sign noting a mile until they reached the campsite.  Truly breaking the silence now, instead of just grazing it, Andrzej was the first to speak, “Wow, we’re almost there.  Kind of crazy how fast time goes when you’re just flying down the open road, huh?”  Stephen couldn’t disagree more.

	“Yeah, feels like it’s barely been thirty minutes since I picked you up,” he lied.

	“Keep an eye out for the gap in the trees.  I heard the sign got taken out by some crazy driver some time ago and it never got fixed.”

	“That’s comforting.”

	“Incredibly.  Next time they’ll just barrel into the trees.” Andrzej paused, ”Don’t be that next time.”

	Stephen chuckled before putting out a thumbs up while holding the wheel.  “You got it boss.  Nothing but drift maneuvers the whole way through.”

	Andrzej gently hit Stephen on the shoulder as he joined in the laughter.  Stephen’s expression softened into a small smile, he’d missed this greatly.  He felt himself ease up on his grip of the wheel.  Just up ahead he noticed the gap in the tree line Andrzej mentioned, that was quick.  By the time they had pulled in and parked the car, there wasn’t too long until the sun would go down.  Before getting out of the car, Stephen looked around and realized they would have the whole place to themselves, as there were no other cars.  Good, he thought, that’s probably for the best.  

	The two quickly began to unpack the car and found a spot near a small fire pit to set up their tents.  Neither had been camping before, let alone set up a tent.  They idly chatted about the nice weather as they struggled to pitch their tents.  Andrzej secretly looked at the instructions for his, while Stephen pushed forward through sheer determination.  Unsurprisingly, Andrzej finished his first and got to work on the fire, sneaking glances at Stephen, who continually refused help.  By the time Stephen’s tent was standing, the sun was almost down and the surrounding sky was quickly losing light.  Suddenly aware of how long it took him, Stephen scrambled over to the fire, where Andrzej handed him a bag of sausages and some supplies to cook with. 

	Stephen, worn out by his previous effort, breathily suggested waking up early to fish in the river nearby.  Andrzej’s eyes wandered over to the fishing poles they brought before finally agreeing.  Then Andrzej made a suggestion of his own, pulling several bottles of alcohol out from behind the log he was seated upon.  Stephen, just enjoying the moment, without thinking, took a bottle in hand and began to drink.  

	The air grew darker and colder as the two finished off bottle after bottle while they chatted and laughed.  Unbeknownst to Stephen, Andrzej had once again already been a few drinks ahead.  For a brief moment, however, their time of gentle revelry had paused and the creeping feeling of tension along the car ride had returned.

	“You were right,” Stephen leaned back and gazed up at the stars above.  Andrzej looked puzzled, unsure of what his friend was referring to.  “About Audrey.”  Andrzej’s eyes widened in surprise.  He never expected to hear those words.

	“No, I was being selfish-“ Andrzej started, before Stephen cut him off.

	“No, you weren’t.  Picking her over you was probably the worst decision I’ve ever made.”

	“Stephen-“

	“Please, I know it was never normal for us to talk like this, but I need to get it off my chest,” Stephen turned his gaze back briefly to Andrzej, with hurting eyes.  

	Andrzej silently nodded and mouthed “okay”, then sat up straight.

	“She ruined my life.  She was manipulative and she was cruel and she lied… so much.  And I believed her.  I gave her the benefit of the doubt every time, even when all common sense says I shouldn’t have.  She cheated, and over and over I forgave her because I thought I was so in love that it was just a bump in the road and we’d be able to fix things… That I’d be able to fix things.  I was so stupid and she knew it.  She had threatened to kill herself if I ever even thought of leaving.  She had me wrapped around her finger.  That was until, as I’ve rationalized it in all the time I’ve had to think since then, she just got bored and wanted a new toy to play with.  One day, she got up and left with a note that it was over on the table.  That’s all there was to it.  I know she’s fine, physically at least.  She was never really suicidal.  I saw her one day in a drug store parking lot with some other guy.  I guess even my family’s money wasn’t enough to keep her around.  It all happened maybe 6 months before you sent me that email reaching out.”

	“Fuck…” Andrzej felt an overwhelming rush of guilt across his entire body.  Immediately he began to wonder if he should have tried harder to break them up, if he could have been better about it, if he could have been able to prevent any of it.  He never imagined she was anything like that.  Audrey always kept up glamorous appearances in public.  He just knew his best friend was around less and less the longer she was involved.

	“I can’t even cry about it anymore.  I don’t have the tears left in me.  I just feel empty.  In an instant my world was shattered.  And over the past couple months I’ve done my best to put the pieces back together but sometimes it just falls apart again.  It’s so exhausting, Andrzej,” Stephen crossed his arms and dropped his eyes to the fire.

	Andrzej didn’t know how to process all of it.  Nor did he know how to help.  In a moment of poor intoxicated decision making, he reached into his pocket and pulled out a small bag of dried mushrooms he had brought just in case.  “They help me with anxiety… and just generally feel better.  This is probably inappropriate but-“

	“Sure, what’s the worst that could happen?” Stephen chugged the little remaining liquid left in his bottle and held out his hand.

	Not thinking he would so readily go with it, Andrzej cautiously dumped some into his hand, split it in half, then gave one pile to Stephen.  Andrzej held back inappropriate laughter as Stephen gagged trying to get it down.  Then came the silence.  They weren’t sure how long they sat there quietly as it felt like hours, continuing to drink and snack on the remaining sausages Stephen had cooked.  Before long though, the two found themselves lying in the grass next to one another a few feet from the fire, looking up at the sky.  Andrzej began to tell stories of what he had been up to in the past two years.  They both genuinely had smiles on their faces for the first time since coming here.  Stephen felt the pain that had been weighing on him all this time lifting away as he forgot about the bad things, if only for this short time.  He felt Andrzej tense up next to him and stop talking.  Stephen looked over to see a troubled expression on his friend's face.  

	“Also… going back a little… just after we graduated, my dad and I were in a car accident.  A pretty bad one.  I ended up only having a few cuts and bruises, but my dad… didn’t make it.  He died on the spot.  Same with the guy that hit us.  Veered into our lane going way too fast.” Andrzej kept his eyes focused on the night sky as he spoke.  “He didn’t even know anything had happened between us.  I’m glad he was able to go out ignorant of it.  Would’ve broke the old man’s heart.”

	Andrzej jumped when he felt Stephen wrap his arms around him.  Stephen held Andrzej tightly as tears welled up in his eyes.  He cried hard, not wanting to let go of his friend.  Andrzej felt it too.  Soon he joined in and put his arm on Stephen.  They had never seen one another like this before, feeling such visceral emotion that they couldn’t help but just cry it all out.  Though they didn’t say it, they were thankful to be alone.  Between breaths, Andrzej tearfully apologized for starting the fight that tore them apart.  Stephen held him tighter and apologized for not listening to his best friend.  

	Over an hour had passed of their embrace on the grass, though the tears had stopped much earlier.  They were both exhausted.  Starting to regain their senses some, wide-eyed, Andrzej suggested they call it a night.  Stephen, realizing he was still holding onto Andrzej all this time later, sheepishly let go and agreed.  The two stumbled upward before making their way to their separate tents a few feet from each other.  In spite of their intense moment of vulnerability, there were no further words between the two that night and it did not take long for both to drift off to sleep.

	Stephen rustled around in his sleeping bag, deep in a terrible dream.  His heart began to race as his body shifted around.  In a swift motion he shot up, frantically scanning around the tent while he panted heavily, trying to regain his bearings.  He put his head in his hands as he thought about that terrible dream.  Each time he shut his eyes — even for a brief moment — he was transported back to it.  Audrey had never been physically violent towards him, but that did not stop his mind from imagining such when he least desired it.  Stephen rubbed his hands together, finally breathing normally once more.  Another scan across the tent made him realize how cold and lonely he felt at that moment.  His eyes then drifted to the right, off toward where he knew Andrzej’s tent was.  Still somewhat under the influence of the evening’s consumption, he remembered laying in the grass with Andrzej and how safe he felt at that moment.  Stephen quickly grabbed his flashlight and stepped out of his tent.  Maybe they could relight the fire and spend a little more time together before going back to sleep.

	Stephen took a few steps towards Andrzej’s tent without yet turning on the flashlight.  He looked down at it in his hands, barely able to see it in the darkness, when he felt a sharp pain in his foot and yelped like a frightened dog.  Stephen immediately fell back into the cool ground behind him.  His breathing was shallow and quick.  Frantically, he fumbled with the flashlight to turn it on and pointed it directly at himself.  Blood covered the bottom of his foot.  He painfully squinted and could just barely make out a shard of glass sticking out.  Stephen’s hands shook as lightheadedness started to overcome him.  His breaths were increasing in speed.  He turned to the tent, flashlight following his gaze, and saw a spread of shattered glass just outside Andrzej’s tent… and the zipper to the tent was wide open…

	Stephen took a deep breath and returned to his foot.  He reached a trembling hand down and gripped the smooth sides of the glass.  Adrenaline was the only thing guiding him as he quickly ripped it from his body and threw it out into the tree line.  Chest heaving, Stephen flipped over and crawled towards Andrzej’s tent, just enough to see inside, making sure to stay clear of the glass shards.  His breathing stopped.  Andrzej was not in the tent.  Stephen whipped his head around, looking all over the campsite from his position.  Andrzej was nowhere to be seen.  Fear began to overwhelm Stephen.  He wanted to call out for his friend, but was suddenly terrified to do so.  They were all alone out there.  He was all alone out there.

	In a panic, Stephen crawled back into his tent and zipped the door forcefully.  He laid down on his sleeping bag, shivering the moment he hit the ground.  Terror wrapped itself around him like a snake, winding and constricting its way across his body.  The lightheadedness returned as he curled up on his side.  His eyes wouldn’t shut if he wanted them to.  He felt as if he was staring through the wall of the tent from how intensely fixed his eyes were forward, but he soon felt a creeping sensation of vulnerability and unease, like his back was open and unprotected.  Without thinking further he flipped over onto his other side, now staring in the direction of Andrzej’s tent.  For a moment the sensation was relieved, but it quickly returned, making him feel that this position was unsafe too.  He fearfully flipped back and forth with tears starting in his eyes, never fully feeling alright enough to remain in one position until he found himself on his back looking at the ceiling of the tent.  It wasn’t perfect, but he felt ever so slightly better.

	Stephen began to try to rationalize the situation in his mind.  Maybe Andrzej was just out in the woods peeing.  He just went off to find a tree that was out of sight.  But why would he go that far if he was the only one outside of the tents and it was super dark out?  And if he did go to the trees, he would’ve seen the flashlight and said something.  But he didn’t, and there would be no reason for him to go deeper-

	Stephen’s rapid thoughts were cut off by the sound of distant footsteps.  They aren’t Andrzej, he thought.  They’re heavier and there’s a strange rhythm to them.  His heart was beating in his eardrums and he contributed to stare directly ahead at the ceiling.  His throat was getting dry and it quickly became more difficult to breathe.  Tears silently streamed down his face.  The footsteps stopped.  Something fell violently to the ground in the direction of Andrzej’s tent.  The sounds from outside stopped completely.  Stephen’s entire body was consumed with denial.  This can’t be real… this can’t be happening… this isn’t real… this isn’t real… raced through his mind over and over again.  The sensation of dread became so intense that Stephen couldn’t help but whisper to himself just to ground himself to reality.

	“I want to go home.  This isn’t real.  This can’t be happening.  I want to leave.  This isn’t real.  This can’t be real.  This can’t be real.  This can’t be happening to me…” he couldn’t hold back any tears as he cried violently while trying to stay as quiet as possible.  The thoughts engulfed in terror continued flowing over him.  He felt like a child lost in a store unable to get help.  He wanted his mother to come save him, to take him home and show him everything would be alright.  A sharp realization came into focus: the car!  Stephen lightly patted his pocket, feeling that he still had the keys.  His breathing was leveling out a little once again.  He turned his head to the flashlight on the ground… it was fairly heavy.  Immediately he imagined making a break for the car.  His heart pounded slowly, yet intensely throughout his entire being and for once he was gaining a sense of control of himself.  

	However, just as Stephen steeled himself to venture out of the tent, a fog of doubt began to cloud his mind once more.  He hated this feeling of rapidly bouncing from chaos to calm and back.  It only made the pain of the situation worse.  What if Andrzej was out there in the woods?  What if that really was him that collapsed at the tent?  What if he needed help?  Stephen’s thoughts were flushed with concern, not knowing what he should do anymore.  He couldn’t just leave Andrzej without looking back.  But what if it’s not him, and looking back would be dangerous?*  Stephen again felt his pulse hasten.  He fell back into his initial state of panic that set off this wretched anxiety.  He grasped onto anything he can to ground himself to reality.  His hand found the flashlight.  He gripped it hard and stared up at the ceiling, tears welling in his eyes once more.  The longer he took to think of a solution, the worse he felt as the panic reverberated through him.  Cautiously, Stephen tried to slow his breathing down, focusing only on that.  It helped if just slightly, as he noticed that outside the tent there was not a single sound to be heard.  No wind rustling the trees, no animals calling out, and no noises from whatever had collapsed.

	Stephen continued to focus on his breathing.  He closed his eyes for the longest time since he re-entered the tent.  He could not let fear overcome him any longer.  He hated the feeling of helplessness that kept him confined to his tent.  He had had enough.  In his self imposed blindness he slowly began to formulate what would be his final plan.  He was going to run to the car, turn the headlights on, lock the doors, then if nothing happened to him he would turn the car to face the tents to see what was laying on the ground.  If Andrzej wasn’t there, he was going to immediately leave to get help.  It had to work.  Stephen took a deep breath, then opened his eyes.

	Bright blinding lights shone through the material of his tent directly toward him.  He froze.  


	“What…..”  All the air seemed to leave Stephen’s body at that moment.  He felt his plan shatter into a million brittle fragments inside his head.  Stephen couldn’t move.  His entire being had instantly become wrought with an unbridled paralyzing terror.  He didn’t know what to do anymore.  His head felt faint.  Without thinking, he acted purely by how his body felt.  He screamed desperately into the night, as loud as his body would allow him.  He did not choose this, it was merely a primal reaction to his state of mind.  He continued to scream, feeling further lightness in his head.  He screamed out for Andrzej, for help from someone he cared for.  For the final time that night he slammed his eyes shut and wept harder than he had ever before.  

	Stephen then felt his body being jerked violently around.  Reflexively his eyes flew open in a burst of panic once more.  His tent was unzipped… and the sun was beginning to rise on the edge of the horizon.  He felt arms wrapped around his body.  He whipped his head around to see… Andrzej with his eyes shut, holding Stephen tightly.  Stephen was confused, he didn’t understand what was going on.  He heart was pounding and tears were still wet on his face.  He was only barely able to get Andrzej’s name out of his mouth.  Andrzej gently hushed him and told him that everything was okay now.  He slowly rubbed Stephen’s back as he explained that Stephen was making noises in his sleep, then started screaming, so he ran over to make sure he was okay.  Still shaken up, Stephen held onto Andrzej tightly.  Stephen began to apologize for all the things he had done wrong over the years, like not listening to Andrzej when he absolutely should have.  But as Andrzej held him close, he insisted that none of that mattered now and that all he cared about in that moment was that Stephen was alright.

	After a short while of letting Stephen calm down, the two sat at their fire pit with blankets wrapped around each of them.  Andrzej had started making them some breakfast and tea with a gentle, but concerned smile.  Stephen leaned back on the log he was seated atop and let out a deep exhale.  He stated that perhaps mushrooms weren’t for him.  After a pause, he suggested that they go for a swim in the river after breakfast.  Andrzej nodded his head and agreed, just wanting to do whatever Stephen wanted to do so he could make sure he was happy.  Andrzej didn’t like seeing Stephen distressed like that.  And truthfully, he never really enjoyed fishing all that much either.

</pre>

<?php include($_SERVER['DOCUMENT_ROOT']."/includes/footer.php"); ?>
