<?php $pageTitle = "SCC-03"; include($_SERVER['DOCUMENT_ROOT']."/includes/header.php"); ?>

<h3>Suncrest County Chronicles #3</h3>
<h1>An Overdue Reunion</h1>
<div class=card>
<pre><i style="font-family: Courier New;">The Sun is not closer.  There, now I’ve said it.</i>

	It was an election year last year.  Pablo sat quietly, his eyes closed with his fingers pinching his scrunched up face, forcing more wrinkles to develop along the sides of his eyes, while pressing his body as deep into the wooden park bench he could.  He had little desire to stand up and leave Yellow Tree Park on his day off, opting to spend some time enjoying the last of the kind summer breeze before its comfort gave way to harsh autumn winds.  However, he increasingly wanted to be away from the conversation he overheard loudly just a few feet away near an old chess board carved into a stone table.  He tried gathering his thoughts over the raising volume of the conversation, debating whether or not he should bike across town to Red Face Park and spend his day there instead.  The tension in his expression eased somewhat as he considered the prospect.  I could grab a sub at the place down the street along my way and have a little picnic under a tree, he thought to himself, still debating his next course of action even though he knew he had already planted the much greater seed of an idea in his mind that would no doubt grow large enough that he’d soon beg his body to fall in line and carry out the bloom.  He lowered his hand from his un-scrunched face and opened his eyes again to survey the area once more just to be sure.  The sudden exposure to light from having his eyes clamped shut for so long was as if he had stared directly into the Sun momentarily.  By the time his eyes adjusted, he became acutely aware of the presence of the conversation once more.  A third person had entered the equation, walking over to the two loud individuals.  The moment she stuck a picket sign into the hardening soil, Pablo abandoned Yellow Tree Park.

	He let out a tired sigh as he spun the cylinders of his bike lock one at a time.  It was a tiredness not born out of sleep deprivation or malnutrition, but frustration.  He was tired of- frustrated at hearing the same inane nonsense more and more as the days had gone on.  Soon it would have been a year since the previous mayoral candidate had taken office.  The new mayor was divisive, but they achieved results.  And those results were divisive, but they created change.  And that change was divisive.  Pablo divided the arm of the lock from its body as he freed his bicycle from its temporary inability to abandon Yellow Tree Park.

	He rode for only a few minutes before reaching his destination and pondered briefly why he had to convince himself to leave Yellow Tree Park in the first place.  Red Face Park was not remotely far away and he had no particular sentimental tie to Yellow Tree Park.  In fact, to Pablo, his new idea sounded much more enjoyable than mindlessly sitting in Yellow Tree Park.  That line of thinking was dashed from his mind, however, when he felt his front tire slip under a maple leaf the color of burnt spaghetti squash.  The disruption took all of his mental processing away from anything else and he quickly forgot and moved onto righting his bicycle, then he continued on to acquire his picnic lunch for consumption in the hopefully more peaceful Red Face Park.

	The sub shop was in the same place it always had been.  Luigi’s, a humble yet beloved staple of Harrison’s community rested solidly upon the foundation of the rock that was in the same place that it had always been.  The establishment was founded not long after the end of the Rif War by a Spanish immigrant to New Jersey named Sergio Solano.  You see, Sergio actually had an uncle named Luis who died in the war, which many believed to be the origin of the restaurant’s name, and thus was meant to honor him in some way.  But Luis and Luigi are not the same name I hear you say.  Of course they aren’t.  Sergio never explicitly said why the building was named Luigi’s and not Luis’s but the common theory among Harrison residents as time passed on is that saying or writing “Luis’s” is kind of hard AND given the strange familiarity Sergio felt living in an area of a state that was heavily Italian, he likely adjusted the name to fit in a bit better with the local also immigrant population while he himself didn’t have any issues because Sergio as a name is of both Spanish AND Italian origin since it originally originates from Latin origins just like the two immigrant romance languages and cultures he felt himself stuck between.  A bit of a peculiar predicament, huh?  Well much to the chagrin of the likely now dementia addled or diseased or deceased residents of Harrison that saw the founding of the joint, Sergio actually had a cousin on his mother’s side that the townspeople were unaware of until recently who lived in Italy and was ethnically Italian who was very much still alive following the events of the Rif War named Luigi!  And as if to spite the very notion of this fact, Luigi’s still stood in the very place that it had always been.

	Disappointment gradually spread across Pablo’s face the longer he stared at the sign in the window of his favorite sub spot.  

	“Don’t listen to his lies!  It IS getting closer!!”

	The sign read.  Its message was not dissimilar to the picket fence that punctured the barrier between the sky and earth of Yellow Tree Park just a short while ago.  Pablo debated in his head whether or not he should continue with his picnic plans.  He could just go someplace else, but after he had constructed the concept of adding a few slices of bacon to an Italian submarine sandwich made with fresh cut ingredients directly in front of him, he found it difficult to draw his mind toward other ideas.  He wanted that sandwich and pizza just was not going to cut it.  Even if he disavowed the nonsensical conspiracies that had spread around town that the restaurant clearly held as gospel, he found himself standing behind the ordering counter all the same.  All he had to do was simply not engage with the subject and order his lunch like normal.  The reconciliation with giving money to an establishment he knew very obviously disagreed vehemently with himself politically was to come later.  The business was fairly empty at that time, save for two other patrons in line before him.  They gave their orders one at a time and made small talk with the man behind the counter, who Pablo knew to be the owner.  Eventually after several minutes of twiddling his thumbs and trying his best not to think about or look back at the sign in the window, it was Pablo’s turn to step up to order.  Only he and the owner behind the counter remained.  Pablo gave the list of ingredients he desired, making extra sure not to forget about the bacon he had dreamed up, to which the owner made a comment about it costing 50¢ extra.  Pablo nodded in understanding as he watched the owner already placing the strips upon the previous foundation of ingredients that sat atop their foundation of bread in the same place it always had been, after his order began of course.  The times he ran the counter, the owner was known to never move the sandwiches he prepared around the plating area, leaving it to sit in one particular spot for the whole experience of meal construction.  Having spoken to the man before and not wanting to come off as rude, Pablo spoke up.

	“It’s a warm one today, huh?  Haven’t looked at the weather channel yet, but I’m hoping it stays like this at least a few more days, maybe come by the shop a little more often and enjoy the Sunlight.” Pablo immediately became aware of the error in his speech.  He desperately hoped the owner had not picked up on it.

	“Gonna have a lot more Sunlight, pal.  The mayor keeps trying to deny it, but we can all see it plain as day-“

	Shit.

	“The days are getting longer even though it’s fall?  The summer’s coming to an end but the weather’s been strangely warm dontcha think?  They are doing it to us.  I’ve lived through my fair share of Indian Summers and let me tell you, it’s gonna be like nothing we’ve ever seen before!  It’s all over the news!” The owner didn’t make eye contact with Pablo as he spoke, lathering the top slice of bread of Pablo’s sandwich with the extra mayonnaise he requested.  The remainder of the sandwich moved not an inch.  Pablo wondered exactly which news stations the owner was watching to have the perspective he did.  It was not a genuine wondering though, as he already knew quite well.

	“Yeah it’s uh… I hope they can do something about it…” Pablo pretended to play along for the sake of his lunch.

	“There ain’t nothing they can do about it buddy!  Don’t you know?!  The friggin’ Sun is gonna collide into the damn Earth!  It’s gettin’ closer and we ain’t gonna be able to stop it!  The real scientists are saying that it’s un-fuckin-stoppable.  It’s an inevitability, they’re sayin’!” The owner threw his hands up in the air, bumping the cutting board upon which Pablo’s meal rested.  The sandwich shifted slightly, but not so much that the owner would’ve noticed in his fit of… frustration.

	“If it’s gonna crash into us, what’re you doing still running a shop?  If you think it’s all gonna burn up then why keep at it?” Pablo let his true feelings surface briefly. The owner held a quizzical expression on his face, as if no one had asked him that before.  He held the top part of Pablo’s sandwich in one hand and a mayonnaise clad butter knife in the other as he crossed his arms in thought.  After a moment of contemplation, his face loosened to a downward disposition and placed the top bread onto the remainder of the sandwich.  He wrapped up Pablo’s meal as he spoke, with Pablo letting out a sigh of relief upon realizing the owner had not hooked onto the word ‘think’ in his second question.

	“Well, ain’t really nothin’ I can do, right?  They ain’t tellin’ us when it’s comin, just that it is.  If I don’t know when it’s gonna hit us, well, I still gotta feed my family, right?  Ain’t nothin else I can do.” The owner’s face was sullen with grief he felt over his lack of power given the situation.  The two silently moved over to the checkout counter.  Pablo handed the owner a twenty dollar bill.

	“Keep the change.” Pablo said before he could be told the price.  The owner was somewhat taken aback by the action.

	“Thanks, man.  Hey and uh, you have a good day, pal.  Try to keep your mind off it all.”  The owner’s words were genuine.  Pablo gave a mock two fingered salute as a goodbye and headed through the door.  The bell above it jingled in the background as he placed the wrapped sandwich in the basket of his bicycle.  He felt off.  Unsure of what to make of the interaction, he shook his head and remembered he had wanted to eat in Red Face Park just around the corner.

	After pulling his bike up to a large tree casting a larger shadow, Pablo sat down and started to unwrap his lunch.  He wiped his brow of sweat with the sleeve of his shirt as he performed the act.  It really is quite hot today actually, even in the shade, he thought to himself.  The warmth did not dissuade him from the picnic he had fantasized about, however, and satisfyingly chowed down on the left half of the sub.  He coughed after swallowing a bite.  The weather was starting to become slightly oppressive as midday gave way to afternoon, the Sun nearing its apex in the cloudless cerulean sky.  Pablo decided that he would return home and finish his meal indoors after consuming the first half.  His apartment would be a reprieve, but no sanctuary, as the property manager had already replaced the luxurious air conditioning with heat.

	“I tell ya it’s the Earth that’s moving, not the damn Sun, ya fool!” Pablo overheard an older white man with an accent yelling across the park.  He looked up mid-chew to see a group of people conglomerated around a central spot on the other side.

	“The Earth?!  You’re saying the Earth is moving toward the Sun?  That’s the dumbest shit I’ve ever heard.  Why in God’s name would we do that?” A woman yelled back at him.

	“The Earth is always moving!  Why wouldn’t it swing around closer to the Sun?  You some kind of stupid, lady?  They clearly sent it off its particular trajectory somehow” A younger man responded.  It was clear from his way of speech that it was his first time saying the words ‘particular trajectory’.

	“Pendejo,” the woman muttered under her breath and turned away as if to leave.  She gripped the top of a sign stabbed into the dirt.

	“What was that?!” The younger man’s tone changed.  He started after her.

	“Stop.  Does anything really change based on which heavenly body is going where if it’s all meant to collide in the end?” A tall man dressed in dark clothing placed his hand on the younger man’s shoulder to halt him.  The younger man looked up and then spit on the ground to his right.

	“Fuckin’ centrists” the young man grumbled as he aggressively shrugged off the hand and stomped away in the opposite direction.

	Pablo still had not taken another bite and yet was still chewing.  He found himself freed from the transfixation of the argument.  He hadn’t considered that there were differing perspectives within the conspiracy theory.  He tugged on his shirt for relief, deciding that he would wrap up whatever he had left and finish it at home.  He took another quick glance back at the scene and recognized the tall man from the conversation in Yellow Tree Park.

	The bike ride back was strenuous.  His heart pounded more than it did all day prior and his hands felt slick against the handlebars.  If he were to fall it was more likely due to a betrayal of his own bodily condition than any outside factors such as a stray maple leaf on the road the color of burnt spaghetti squash.

	Pablo’s chest heaved as he tried to listen to the advice of the owner of the sub shop, but he couldn’t not think about it.  He was feeling the impact of it.  It was so unbearably hot.  His mouth felt dry and his tongue was crisp against his teeth.  There was a growing flame in his lungs.  He couldn’t bring himself to look upwards as he could hardly just focus on the road in front of him.  How could he think about anything else?  It was the only thing that mattered in this movement and everywhere he went it was right in his face.  Not just now, but before.  Before with the people in the park and the owner of the shop and the people in the other park and the pundits on the news and the reporters in the papers and the teens at work and yesterday when his girlfriend called him and said she needed to meet up and talk about something important soon.  Was that what she had needed to talk about?  What else could it be?  What could be more important than what was going on right at that very moment?  

	Pablo did not know whether the Sun was going to crash into the Earth or if the Earth was going to crash into the Sun.  He did not care.  It did not matter.  The only thing he did know for certain was that HE AND THE SUN WERE GOING TO CRASH INTO ONE ANOTHER.

	Pablo released his bicycle upon reaching the door to his apartment.  It tumbled to the ground away from him.  Though the thought had not even crossed his conscious mind, he knew he would not be able to retrieve it.  His hand fumbled for the keys in his pocket.  As he raised his glistening left to the door he clutched his chest with his right in hopes to suffocate the conflagration blazing inside of him.  They keys slipped from his shaking fingers and at once he felt as if his life were to end at that moment.  However, his moist ring finger caught the lanyard attached to his keys by… an act of God?  Or was it just sheer luck?

	Again, Pablo moved the keys to the keyhole and felt a brief but incredible sensation of relief as he felt the teeth slide against the pins of his door lock.  Struggling to breathe, with the same motion that he twisted his wrist to unlock the door, Pablo’s face collided with the words ‘Welcome Home’ where his feet once stood.

</pre>
</div>

<nav>
    <a href="05.php">← Previous Story</a>
	<a href="07.php">Next Story →</a>
</nav>

<?php include($_SERVER['DOCUMENT_ROOT']."/includes/footer.php"); ?>
