<?php $pageTitle = "SCC-07"; include($_SERVER['DOCUMENT_ROOT']."/includes/header.php"); ?>

<h3>Suncrest County Chronicles #7</h3>
<h1>She Would Always Call Him "T"</h1>
<div class=card>
<pre>	School was cancelled, again.  It had been snowing for nine days straight.  The temperature never got warmer, but there would always be a thick sheet of ice under the freshly laid snow along the roads.  “Too dangerous for students to travel on”, the principal said.  It wasn’t just us, it was also all the nearby schools in the county from what I heard.  I’d bet all of New Jersey and New York and Pennsylvania had school closings.  Mom and Dad said we’d probably not get a spring break anymore… and that if this kept going on that we’d get days added onto the end of the school year.  I was pretty upset thinking about that to be honest.  I didn’t do anything to cause this… I wasn’t skipping school… I was a good student.  I did my homework, I got good grades.  Unlike my little… brother, Thomas.  He was infuriating, especially during the snow days.  We were supposed to go out and have fun and enjoy ourselves and just… love… the snow.  I know I did.  Yet, he was bumbling around like he didn’t know how to feel about the darn stuff.  <i>I, for one,</i> was obsessed with snow.  Mom and Dad hated it.  It made going to work basically impossible so they stayed home most of the time unless the roads had been cleared early.  On those occasions they let us stay home alone together as long as I looked after… Thomas.  What did they take him for?  He wasn’t a baby anymore!  He’s been growing up!  He didn’t need a babysitter, but even if that were the case, I certainly did not want to be one.  

	God, Thomas just… couldn’t get it through his head that snow is <i>good</i>.  It’s <i>pretty</i>.  It’s <i>fun</i>.  But when I went outside to go <i>enjoy it</i>, dad would send him off with me.  I couldn’t just enjoy it.  It would make me roll my eyes every time.  I’d go off and do my own thing only to get hollered at from an unhappy parent tapping their foot on the deck.  Each time, I’d groan and trudge over to… him across the pale abyss.  And so I would TRY to engage, but every time it was met with inefficiency.  We started trying to build an igloo, but I was faster and would get worn out because I was doing all the work.  It was frustrating.  It wasn’t <i>fun</i>.  We would have a snowball fight, but the moment I hit… him in the face, nothing but tears as far as the eye could see.  Somebody would think the kid sprung a leak.  If I got hit in the face with a ball of sweet powdery snow, I’d be happy about it.  I LOVED the stuff.  Winter was my favorite time of year.  Snow was my favorite.  The way the light blinded you during the daytime from the sun reflecting off of its fresh untarnished surface, the way it crunched when it was finally underfoot, the way it felt on my tongue when I ate a mouth full of it.  I would have snow year round if I could help it.

	I didn’t mind school being closed.  I got to spend more time with friends than usual.  We would all take sleds and go to the rock hill down the street.  It wasn’t a hill covered in rocks, there was just a big one at the bottom.  It was covered in grass.  Well, it was covered in snow.  On top of the grass.  But the rock was still visible.  Obviously.

	Dad tried to go off to work, but mom stayed home that morning and made us breakfast.  Fresh strawberry pancakes, my actual favorite thing to eat.  Mom would wake up extra early to make the batter herself from scratch and would always cook them perfectly on the stove.  Now, she knew what she was doing.  I must have asked her to make them so many times that she had it down to a science.  Thankfully when we lost power near the start of the storm it only lasted two days.  Mom said that the stove would’ve worked fine anyway since it was gas.  Still though, I preferred when the toilet flushed properly.  PSE&G was always pretty good about squaring those things away.  There was an old dead tree near Kayla’s house that was just waiting for some giant to come and kick it down.  I guess the weight of all that marvelous snow was too much for it to handle.  Snapped right at the base, dad said.  He went to check it out when it happened.  He said that nobody got hurt and there was no property damage, but their dog was in the backyard and got squished by the tree.  I didn’t go over there much so I didn’t know him well.  A little pug named Buggy, I think.  Yeah, he definitely looked like a Buggy.

	After breakfast, Mom was trying to convince me to help her shovel snow when Kayla, Danny, Brandon, and Gina knocked on our front door with their sleds.  Literally whacking their sleds against the doorframe.  I think Mom knew her bargaining would fall on deaf ears at that point.  I felt a little bad since she <i>had</i> made the pancakes for breakfast, but I couldn’t just not go out with them.  When she let them into the living room I noticed that Danny’s little brother Kyle and Kayla’s little sister Megan were standing behind them.  They were a little bit younger than my own sibling.  Once I saw that however, I could practically hear the cogs turning inside my mother’s head.  I whipped around to try to stop her before she could open her mouth, but it was too late.  She was already getting coats for both myself and… Thomas.  Danny offered me silent condolences since he knew the feeling well.  

	I didn’t want to fight in front of my friends, so of course I begrudgingly accepted it.  No sooner than when they had arrived, we were all out the door, kitted out in our finest snow gear, ready to tackle the hill.  Gina’s parents were kind of rich.  I’ve been to her house a bunch and they were not afraid to show it.  She had pinball machines and skeeball in their finished basement!  I don’t even know how they got it all down there, the basement door wasn’t all that big, but it was down there nonetheless!  So of course Gina had a nice big inflatable inner tube to take the hill with.  It was big enough that two of us could go on it at once and because of that she made Brandon carry it.  He kind of had a thing for her.  Little bit of a doormat at times, but I thought they would’ve been cute together.

	The rock hill wasn’t exactly far away, but the large amount of snow made it tough.  We were nearly exhausted by the time we got to the top of the hill.  Danny cursed under his breath about the fact we’d had to climb back up the hill after going down.  All of the little siblings turned to look at him with a look of horror at his word choice.  He shot them back a glare that said “Don’t you dare go telling”.  Danny and Kyle’s parents were pretty strict.  I wouldn’t swear around my parents out of principle, but theirs expressly forbade it under threat of a belt or a spoon.  Our parents would never hit us, but if they ever tried I’d make sure they couldn’t get to… Thomas.

	Gina shook me from the little rabbit hole my brain had been crawling down and told me she wanted to go down the hill with me  in her tube first, as customary.  Beyond the games in her basement, the main reason I had gone to her home so much was that Gina had been my best friend since we were very little.  We were in first grade when she moved to Teneborough.  She was like a moth to a flame that was scared of the dark with how she clung to me at first.  I’m not sure what it was, but we just clicked.  Her parents thought it a bit strange, knowing their daughter’s only-child behavior, but ultimately were glad she had made a new friend so quickly.  So as tradition, we took it upon ourselves to always take the first ride down the rock hill together.  We saluted our friends as Danny pushed our sled toward the edge of the summit of the hill… and down we went with the wind in our hair.

	Without warning, I tackled Gina off of the tube as we neared the bottom, sending us flying one direction and the tube in the other, toward the titular rock.  We landed with a fluffy thud just as the tube bounced hard against the rock.  We were both face down in the snow, absolutely caked in the stuff when I heard what sounded like a cry come from beside me.  I quickly got up and flipped Gina over only to be deceived by what was the start of a very loud cackle.  The five of us were no strangers to a little rough housing, but I never wanted to push it too far and sometimes worried that I would on accident.  I swore at her and threw a fistful of alabaster mist in her face, which made her laughter only grow as she tried to bat it away.

	Brandon yelled down to us that he and Danny were on their way.  One after another, they plummeted down the hill, eager to meet up with us.  Kayla wasn’t far behind, though she seemed caught off guard by the others’ quick departure.  The snow was deep enough that all three of them slammed together in a pile up without much cause for concern.  We hoisted ourselves up and I went to fetch the inner tube, with Kayla not far behind.  She said it was big and wanted to help carry it.  I told her I could handle it since it wasn’t heavy, but I wasn’t going to say no to help.  She told me about how her dad argued with the PSE&G people about keeping the tree once they had gotten it off of the power line.  Apparently he thought that was the perfect opportunity to hack it to bits for firewood and had been going a little bit at a time each day.  After he finished, he was planning on bringing some to all the houses nearby as an apology for not taking the tree down earlier.  She and her mom decided that they would bake some cookies to go with the firewood to help everybody feel better about the weather.  I not so subtly suggested that she should tell her mom to make sugar cookies, my other favorite food.  I could annihilate a box of those like it was nobody’s business if I really wanted to.  Honestly most of the time I really wanted to, but alas, my parents would never allow that to happen.

	Once we had completed another few runs, we all sat perched atop the summit munching on granola bars Mom had packed for us.  I couldn’t deny that I was in need of some extra energy after climbing back up the hill several times.  There was a lull in our chatter for a moment, which was when I heard Kyle start to ask Danny about Thomas.  Before I could even process the words to be upset, Danny had whipped his head around and yelled at his brother to shut up.  The outburst only drew more attention to them, but Danny clearly felt confident he did the right thing, and I appreciated him for it.  I cared for my sibling as any sibling would, but sometimes he made situations needlessly difficult.  All the questions people began to ask started to frustrate everyone involved.  All my friends knew.  It took some time for them to get it, but they understood.  It really did mean a lot that they stood up for him, but in another world that wouldn’t have even been necessary in the first place.

	Once the air had been thoroughly sucked off the hilltop I scarfed down the last crumbs of my granola bar and suggested we get back to the sleds.  Truth be told it did not take much convincing, but I wanted to race.  I could tell Brandon wanted to go down the tube with Gina, so I spared him and redirected my challenge to Danny, who eagerly accepted.  Kayla took off a glove and waved it in the air like a race girl’s flag.  On her count we took a running start and dove into our respective sleds, careening down the hillside.  I felt electric.  The hill was tall, so I had time to survey my opponent and the surroundings as we descended.  I looked to see where Danny <i style="font-family: permanent marker;"><b>XXBROFEPEGDGDPXDOWGDDORGSGFWHELGJWHWGECDDKWOSXHDWOXORPFWGWGEHXOSWPRGEODPEHWFECEIDPREHGEDRRTEFFHEOFPGHWEBBFOEPWUSNNTMQBEDSXPWBSGEOSDOFIFJSDFOISJNIUXI</b></i> that my name was shouted across the hillside by who I can’t recall, but it snapped me to attention.  I was catapulting myself toward the rock.  I tried turning the sled away to recover, but ultimately had to bail instead.  The hard plastic of the sled cracked against the rock when it collided.  Mom was not going to be happy we damaged one of them.  Trying to collect my thoughts, my body felt hot and I could hardly breathe.  I hadn’t even realized it at first, but I must have hit a large root or something as I bailed, because the wind was squarely knocked out of me.  It felt like adrenaline was coursing through my very soul.  I ripped off my gloves and shoved my hands in the snow while heaving for air.  Danny ran over to me and yanked my hands out.  He put a hand on my back to rub and pat, asking if I was okay.  Once I could breathe a little more normally, I asked if he felt that going down the hill.  He had no idea what I was talking about.  He suggested that maybe I was tired and we should head home, but I was defiant and assured him I’d be okay.  I stood up and raised my fist in the air to the cheers of those still at the top.

	We continued on as before from there, taking turns, doing the occasional race, not paying any mind to our siblings.  I proposed that Brandon and I take the tube, as that combination had yet to occur.  Brandon’s mom left when he was real little.  Only recently had his father had any real success when it came to getting married again.  He had a girlfriend that was very nice to Brandon from what he told us.  He had said that he found it weird suddenly having a “mom” when all his life that wasn’t a thing.  His dad wasn’t home much either.  He worked full time making computers or something, which is probably how he was able to raise three kids by himself for so long.  Brandon had two older siblings: a brother and a sister, John and Bella, twins.  They were inseparable from what he said and that they live together off campus and go to the same college.  A little weird in my opinion, I don’t think I could ever be that close with my sibling.  Danny also has an older brother too, named Henry.  I’ve been over to Danny’s a few times but never met him.  Henry was the shut-in type, barely left his room, barely existed as a member of the household as far as I was aware.  He was also pretty clean, so much so that anybody would be forgiven if they thought that Henry was just made up by Danny.  Again, I’ve never seen him, so anything is possible at this point.

	Brandon and I went down the slope along the paths we had carved into the powder by our previous rides.  If we were on a plastic sled, we surely would have gotten locked into one of those predetermined routes.  I felt… good.  It was a snow day after all, what was there not to feel good about?  We didn’t rush on our descent, taking our time enjoying the atmosphere and the vibes of late January.  A splatter of red shot across my periphery.  It took a moment for me to crane my neck back around past us and asked Brandon if he saw it.  We both looked behind only to be greeted by nothing but flavorless flakes of coconut gradually accumulating along the hill.  The tube bumped into an embankment we had unintentionally piled up over the day, signaling the end of our ride down.  Brandon asked if I hit my head earlier, not as an insult, but out of genuine concern.  He was a sweet kid.  I shook my head when we heard a cry from atop the hill.  This one was real.

	We ascended as quickly as the snow and exhaustion would allow.  Kayla was mid sled as we went up.  Danny and Gina were rushing over to our siblings.  That must have been where it came from.  I doubled my efforts, leaving Brandon behind.  Before long, I was able to push past the two above, ready to confront whatever I needed to.  Thomas was crying.  He always was… sensitive.  Seeing that the other two children were very clearly not crying, I had a pretty solid idea of what went down.  I got <i>loud</i>.  Louder than I think any of my friends had seen me before.  Kyle ran over to Danny, clinging to him in spite of his older brother’s protests, also upset by the behavior.  Megan looked like a deer in headlights when she realized Kayla was at the bottom of the hill.  Both Brandon and Kayla arrived at the confrontation together, confused and trying to get caught up.  He had turned around to help her ascend.  Gina turned to them and whispered a summary of the situation and they quickly understood.  Kayla too was not happy.  I held Thomas close and apologized on their behalf while my vision shot daggers at them.  

	Brandon, being the least involved with all this, suggested that it finally was time to head back home.  There were no protests.  We assembled our things and started our journey back.  Danny and Kayla walked up front with Kyle and Megan.  Gina gave Thomas a little hug and said some kind words, then the remaining four of us held up the rear.  She would always call him “T”, even when it made him blush.  It was a cute, but appropriate nickname all things considered.  Tensions slowly lowered and we were back to chatting casually, complaining about the walk, and trying to come up with other people we should invite to do this ranked by how likely their parents would be to drive to Teneborough proper.  Kayla’s house was first along the frosty sidewalks.  She and Megan excitedly waved goodbye, though it was clear Megan still felt some kind of awkwardness from earlier.  Soon after came Brandon’s house, before Gina’s, then mine, then Danny’s.  Brandon shuffled with his arms wrapped around his sled along the ice that had built up between the rocks of his unpaved driveway.  It was only then after Brandon had closed the door to his home that Gina asked where Thomas was.  The four of us spun around, nearly crashing to the cold concrete.  When I locked eyes with Gina after I <i style="font-family: permanent marker;"><b>SDVXODPFIWVEODODGWHWGXDOXPWEHRODJWBDGEPZHEGEVXPZPEGWFENTOSOSHWBRJTOYVDBZXPSHWBTOTOTHSBSNSIDTOORBANSXISOAXYDTSBRBTOTPSHWYWBZOXUSTWBEOFPTHSBDISYDUDBTHSOXAODBRBTJSPSYSGSBRBTKSPSJSBSBTKDOSOSHXBEVTSHXOAOWBWBQTDHXIEOPSBXUDUDOSPRHWNFUSGWOSYXBZIDPDIQGEBTKTPSDYSBDKFORYSBTNSOAUSTSKWNDVXIXTSOWQIDHSPFIABSIDOATABXKWODUXTAJSBXOSPDFIEGHTJSOAUSBSJSOXXUSJEJTPANDJTODJEBTJOZIXHWHABTBRKXOZUWBXHSOQOSIRBRBFX</b></i> must have caught me before I hit the ground.  I blinked hard with haggard breath in a state of panic.  My eyes darted around to figure out what was going on.  Danny patted my back while I coughed up a lung.  Gina said that I blacked out.  She was squatted beside me with a wicked look of worry written across her face.  They both helped me to my feet while Kyle looked on in horror from a few feet away.  He clearly wasn’t capable of handling any part of what was going on and I didn’t blame him.  

	We decided it would be best if we retraced our steps and went back to the rock hill.  Thomas could have just slowed down and gotten left behind.  That behavior was exhibited a fair few times in the past.  We did our best to move quickly and not topple to the ground in a katamari of collective cold as we descended the sidewalk toward our destination.  

	But the rock hill had arrived too soon.  Perhaps it was the increased adrenaline with each step closer that muddled our minds, but the fact we hadn’t seen Thomas along the way certainly screwed with our heads.  Then came the most confusing part.  Danny decided it would be a good use of time to track the footsteps in the snow along the sidewalk to see where it was that he broke off from us.  Gina and I were more pressed to search the surrounding area, but he insisted, so he and Kyle split off.  I wish I had taken Danny more seriously in that moment.  Thomas had fairly small feet for… his age, I wonder why.  That fact coupled with the tread of his snow boots being pretty distinctive compared to the rest of ours would have made that search simple.  There was a flower pattern in the tread of those pink boots.  He didn’t like them anymore, but that was all that would fit.  The only issue was that, upon the brothers’ return, we learned that they <i>couldn’t</i> find Thomas’s footprints <i>at all</i>.    Everyone pivoted their search to this very crucial piece of information.  Eventually we came to the conclusion, however strange, that the likely last steps made by my sibling were still atop the peak of the hill.  There was nothing leading to the sidewalk when we departed.  I didn’t understand how that was possible.  Gina hugged him on the sidewalk.  And we all walked down the sidewalk to get to the hill in the first place earlier in the day and there was <i>nothing?</i>

	At that point the only other thing we could think to do was get our parents involved.  We carefully rushed up to Kayla’s house and her father, while confused, let me use the landline.  Danny briefed him and Kayla while I spoke to Mom.  Mom likely broke the speed limit by… let’s just say she broke it to get to us.  She was a wreck, clearly not prepared to leave the house, still in her slippers.  She pulled Kayla’s dad aside and I overheard her say she hit an embankment of snow along the way.  The car was fine but she wasn’t.  They called the police and then afterward she called Dad at work.  There was an accident on the highway and he wasn’t able to get home.  I had never seen Mom cry like that before, especially in front of strangers.

	It really started to mess me up.  I had a sense of panic, but the dread started kicking in.  The fear.  Where did my brother go?  What happened to him?  What was… happening to my head?  I laid down on the plush olive green couch in their living room.  The floor below it was a rich mahogany color of hardwood that contrasted well against the pale yellow of the walls.  The wallpaper was… not quite beige.  It had more sunny tones to it than that.  Kind of like the yellow Easter M&Ms, but not completely.

	Immersing myself in the decor of the room was the only thing managing to keep me from falling down the same pit as Mom.  Once I realized that, I forced myself to lean into it harder.  Navy blue blanket draped over the back of the couch, knitted, not soft, but still warm, like an afghan.  Maroon… no, burgundy recliner in the corner, facing toward the coffee table.  Metal legs and frame with a glass top.  Like one you’d see outside on a deck, but inside.  I couldn’t believe the police were getting involved.  It was… so serious.  Was it my fault?  Was I a bad sibling?  Did I take him for granted?  Did I complain too much about all of his new… situations?  I didn’t care who they were, I just wanted them back.

	Kayla’s dad put his arm on my shoulder, making me sit up at attention.  The police were here and they needed to take statements.  He said that the others were waiting for me in the kitchen.  Did that mean they walked past me and I didn’t notice?  How could I not have noticed when I was looking at every little thing?

	I groggily rose from the couch to meet my friends sat at the kitchen table with a police officer standing close by.  Kayla’s dad walked in behind me.  One by one we walked over into the dining room and gave our statements.  I couldn’t even remember what I said after my turn had concluded.

	Three days later, school was finally able to open again.  Mom and Dad were in no state to drive, so I walked.  I knew I couldn’t just… not go.  I hated missing school.  I hated having to catch up on work.  I hated being behind.  Maybe it was that hate that enabled me to make it through the day.  The week.  The month.  The rest of the semester.  By then it was a foregone conclusion.  That hate kept me going to school and staying on top of things.  Some days I even forgot about my brother.  There were rumors that one of his shoes had been found a few years later.  I was surprised that anybody remembered what happened all that time after.  It made stomach acid well up in my throat.  We just stopped talking about him after a while.  I missed him, but it would have sent Mom into a spiral if Dad or I said anything.  Some days I could hear her crying in their bedroom.  After long enough though, that too stopped.  I went to college, found myself in a relationship, we moved into our own place, life was going well.  It was going incredibly, actually.  I think I had genuinely put all of that behind me.

	My partner and I were visiting my family for Christmas one year.  That was the first time we spent it with mine.  I didn’t visit my parents often due to the distance, but we kept in touch.  We drove up that old hill, the rock worn down some and spray painted by some teenagers, probably.  I rolled my eyes at it until I noticed something strange sitting on top of it.  There hadn’t been much snow for a while.  Quite the opposite of a white Christmas actually, it was lightly raining.  

	I pulled over the car and claimed I had to go look at something.  My words were met with confusion that followed me out of the vehicle.  My steps through the wet grass spread further and further apart the closer I got.  Sitting on top of the rock of the old rock hill was a small pink snow boot with a flower pattern in the tread.

</pre>
</div>

<nav>
    <a href="06.php">← Previous Story</a>
	<a href="08.php">Next Story →</a>
</nav>

<?php include($_SERVER['DOCUMENT_ROOT']."/includes/footer.php"); ?>
