<?php $pageTitle = "SCC-08"; include($_SERVER['DOCUMENT_ROOT']."/includes/header.php"); ?>

<h3>Suncrest County Chronicles #8</h3>
<h1>It's 10 PM</h1>
<div class=card>
<pre>	The internal cathode ray tube of the television hummed behind the crunchy old speakers that blared the sounds of a rerun of a sitcom that no one in the house particularly cared about.  The canned laughter was not accompanied by a joyous audience, but instead was barely audible to a single mother vacuuming her kitchen the next room over.  The baby blue bag slowly inflated with its gradual accumulation of dust and detritus in the corners and edges of alleyways between worn appliances.  She hummed to herself softly a tune she had heard on the wireless that morning while she carefully cut the crust off of her children’s sandwiches before they woke up for school.  The sun had been down quite a while already, but she had gotten lost in housework and missed watching the sunset entirely.  The kids were out with friends so she took the opportunity to make the most of the peace, only allowing the sounds of the crickets chirping from outside the cracked windows to comment on the quality of her cleaning.  As she maneuvered the base of the vacuum around the dining table, she felt the cord catch underneath the leg of a chair.  Initially thinking it was just minor resistance, she pushed onward only for the plug to pop out of the outlet and smack against the linoleum.

	“It’s 10 PM.  Do you know where your children are?” 

	The broadcast on the television was interrupted by a prerecorded message from a local newscaster.  She chuckled to herself softly and let her gaze drift to the clock on the wall.  The second hand ticked just past the apex of the circle.  It was always perfectly on time every night, even if it interrupted another show.  Of course she knew where her children were.  Diane was at the drive-in with Grace and Elizabeth.  Michael was on a date with Betty at the county fair.  George was staying over at Richie’s house.  All but George would be home relatively soon and her break from the hustle and bustle of raising three kids would come to an end once again.  She encouraged them to go out and enjoy their youth, a far cry from how their father probably would’ve parented them had he still been alive.

	She made her way to the wall where the plug fell and inserted it back into the outlet, reviving the relentless whirring of the vacuum.  Beside the outlet was a hutch with a framed photo of her late husband, Dan.  She knew he would never have been a good father, but she had loved him in spite of it.  She had wanted to be a mother ever since she was a little girl and wondered how she could’ve ever married a man like that.  Then she would reminisce on the times they spent together before the kids.  He was handsome, strong, and a real pillar of the community.  Always the outgoing one, he was quick to speak, but slow to think.  He’d often say some things he didn’t mean.  That’s what she told herself at least.  It wasn’t long after George was born that Dan was drafted.  Even less had passed by the time she received the letter informing her of his death.  She was still a fairly young mother at the time, but that felt like a distant memory to her now.  George was almost 8, she was practically a different person.  She let out a long exhale and returned to the running vacuum in the middle of the kitchen.

	“It’s 11 PM.  Do you know where your children are?” 

	The speakers blared above the droning white noise of the vacuum.  She turned her head after gripping the handle to inspect the rickety television.  It was the same newscaster as always.  Did she hear that right?  Eleven PM?  It just turned ten.  Her eyes swung around to the clock once more.  The hour hand had just barely creaked past the 11. 

	She let go of the handle and poured herself a glass of water to ease the dryness in her throat.  Her local stations must have recently started putting out a second reminder to keep parents in check.  Time tends to fly by when no one is paying attention to it.  The logical thoughts calmed her mind.  She flicked the switch on the vacuum and sat down at the dining table so she could examine the floor for imperfections.  The doctor told her she needed glasses, but she didn’t believe that nonsense.  She never could forget the time Dan had made a comment that a secretary at his work had gotten new glasses ruined her face.  She knew she didn’t need glasses, she could see just fine.  It had been a long day.  She rested her face in her hands for a moment, preparing for the inevitable need to burst forth with energy when one of her children stepped through the front door.

	“It’s 12 AM.  Do you know where your children are?” 

	Her head shot up with a different kind of energy.  She could see the television from her seat.  It was the same caster as always.  The clock showed midnight.  Had she fallen asleep?  She was tired but not that tired.  She got up quickly, being mindful of the vacuum cord that was… wrapped neatly around the cord retainer on the side.  She must have done that after she turned it off earlier.  Or had one of the kids done it?  She honestly didn’t expect Michael till be home till late, but it was late.  He had school the next day.  Diane’s movie should have ended not long after 11 though.  The drive-in was only about 20 minutes away and she said she’d be back right afterward.  Maybe they had gotten home and chose not to wake her.  She made her way to the large window overlooking the front yard.  As she parted the curtains she concluded Michael was still out because he had the car and the driveway was empty.  Her thoughts on Diane then, her bare feet padding up the hardwood staircase and found herself outside Diane’s bedroom.  The door was closed.  She knocked once lightly and waited for a response.  After not hearing anything, she knocked again slightly louder.  If there was anything her kids had taught her, it was to knock twice before entering and she certainly did not forget that lesson.  The second knock had come with no answer, so feeling confident that Diane was asleep, she quietly opened the door to see her daughter… nowhere to be seen.

	“It’s 12:30 AM.  Do you know where your children are?” 

	The voice was muffled by the plush floor below her bare feet.  Her heart pounded in her throat.  She shook her head, thinking that the girls probably went out for a quick bite at the diner afterward.  She had done it plenty of times when she was in her twenties.  Grace had her license so it wasn’t out of the realm of possibility.  She knew she’d have to chastise her daughter when she returned home though.  12:30 on a school night was far too late to be out.  

	She descended the stairs, hand caressing the ornate railing, then twisted the knob on the television, cutting off the picture of the show she was never really paying attention to.  She packed the vacuum cleaner up and stored it back in the closet, then went about closing all the cracked windows around the first floor.  She made it to the sunroom when she noticed that there was a gentle crackling coming from the wireless on the window sill.  Laughing at herself, she realized she must have forgotten to power it off when she started cleaning.  She picked the device up and reached for the knob to preserve its battery.

	“It’s 1 AM.  Do you know where your children are?” 

	She screamed as the portable radio left her fingers and smashed into bits across the pale hardwood.  A tiny piece of metal from the inner workings of the musical device nicked her big toe.  She felt a pinch but thought nothing more of it.  She truly must be tired.  It was such a long day.  Up at 5 to make the kids’ lunches and nothing but work work work all day long.  She shook her head and rushed off to find a broom.  After acquiring one, she hurriedly swept up the mess of a machine and dumped it in the trash.  Her heart hadn’t stopped its rapid racing, pounding against her rib cage the entire time.  The broom did not leave sunroom.  

	Upon returning to the living room, she glanced at the clock.  1:10 AM.  Collapsing on the couch was the only thing she felt she could do.  After sinking her face into the old leather, she looked up slightly and what met her gaze was the light green landline resting atop its end table.  Of course, she should call Grace and Elizabeth’s parents and see if the girls had gone back to either of their houses without saying anything.  She sat up on the couch with her legs crossed and dialed the number to Grace’s house.  It rang for a long time.  She fidgeted with her feet with her free hand absentmindedly while she waited.  When the phone took her to voicemail, she felt a strange substance between her fingers.  She looked down and gasped.  There was blood dripping from where the metal fragment had hit her.  Her eyes darted around the living room and the kitchen beside her and she suddenly became aware of the fact she had been tracking blood throughout the house the entire time.  How had she not seen that?  With great force she lifted herself to find a bandage and clean up the mess before the children came home and saw some sight out of a horror film.  The phone fell to the cushion of the couch unceremoniously when the wire connecting it to the base gave resistance.  A click.

	“It’s 1:30 AM.  Do you know where your children are?” 

	The newscaster’s voice was audible and clear, echoing from the telephone.  She whipped her head back to the couch so fast her whole body went with her, slipping in the bloody track on the ground.  The side of her head slammed against the hutch on her way down.  The plates atop it rattled and Dan’s photo toppled to the floor, glass cracking on impact.  Tears began to well up in her eyes.  She was in a lot of pain.  She felt horrible.  She looked horrible.  The house looked horrible.  Dan looked… bad.

	“It’s 1:45 AM.  Do you know where your children are?” 

	The receiver recounted the adage to her once more.  She didn’t.  She truthfully did not know.  She had no idea where on earth her children were.  Is that what they wanted her to admit?  She screamed into the receiver demanding to know who was on the other line and what they wanted from her.  She pulled on the line as hard as she could in rage and exhaustion as if she was trying to yell deeper into the ear of whatever was on the other side.  She pulled so hard it disconnected.  The recoil from the tension of the wire snapping launched the telephone directly into her face.  She fell back, slamming her head against the linoleum of the kitchen floor.  She had never broken her nose before and for a brief moment wondered if that’s what it felt like.  She began to sob uncontrollably.  Never before in her life had she been so confused and upset and powerless about something she knew nothing about.  Her mind felt light as blood now trickled down from several gashes in her head.  What would the children think when they walked through the door and saw her?

	The television flicked on.  Her vision careened to the direction of the sound while she held onto the coffee table for support.  The effort sent flecks of blood flying across the living room.  Deep down she already knew what would be on the screen before she had locked her eyes on his twisted smile.

	“Brandy, do you know where your children are?”

</pre>
</div>

<nav>
    <a href="07.php">← Previous Story</a>
	<a href="09.php">Next Story →</a>
</nav>

<?php include($_SERVER['DOCUMENT_ROOT']."/includes/footer.php"); ?>
